// Realistic mock data for Crewmatic — Lansing, MI restoration contractor
// This file is the single source of mock data. Swap to real API calls in hooks.

import type {
  JobDetail, Room, Photo,
  Event, DashboardKPIs, PipelineStageData, PriorityTask, TeamMember,
  ReconPhase,
} from "./types";

// ─── Helpers ──────────────────────────────────────────────────────────
const uuid = () => crypto.randomUUID();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 3600000).toISOString();
const dateStr = (n: number) => new Date(Date.now() - n * 86400000).toISOString().split("T")[0];

const COMPANY_ID = "c0000000-0000-0000-0000-000000000001";

// ─── Jobs ─────────────────────────────────────────────────────────────
export const mockJobs: JobDetail[] = [
  {
    id: "j0000001-0000-0000-0000-000000000001",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260324-001",
    address_line1: "123 Oak Street",
    city: "Lansing",
    state: "MI",
    zip: "48912",
    customer_name: "Jane Smith",
    customer_phone: "(517) 555-0142",
    customer_email: "jane.smith@email.com",
    claim_number: "SF-2026-4521",
    carrier: "State Farm",
    adjuster_name: "Mike Johnson",
    adjuster_phone: "(517) 555-0199",
    adjuster_email: "mjohnson@statefarm.com",
    loss_type: "water",
    loss_category: "2",
    loss_class: "2",
    loss_cause: "Dishwasher supply line failure",
    loss_date: dateStr(3),
    home_year_built: 1975,
    status: "mitigation",
    floor_plan_id: null,
    assigned_to: null,
    notes: null,
    tech_notes: "Lifted carpet and pad in master bedroom. Flood cut drywall 2ft from floor. Applied antimicrobial treatment to all exposed surfaces. Wore N95 respirator and Tyvek suit.",
    latitude: 42.7325,
    longitude: -84.5555,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
    room_count: 3,
    photo_count: 42,
    floor_plan_count: 1,
    line_item_count: 0,
  },
  {
    id: "j0000002-0000-0000-0000-000000000002",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260323-002",
    address_line1: "842 Maple Avenue",
    city: "Flint",
    state: "MI",
    zip: "48503",
    customer_name: "Robert Chen",
    customer_phone: "(810) 555-0234",
    customer_email: "rchen@email.com",
    claim_number: "ALT-2026-1198",
    carrier: "Allstate",
    adjuster_name: "Sarah Williams",
    adjuster_phone: "(810) 555-0288",
    adjuster_email: "swilliams@allstate.com",
    loss_type: "water",
    loss_category: "1",
    loss_class: "2",
    loss_cause: "Frozen pipe burst — second floor bathroom",
    loss_date: dateStr(5),
    home_year_built: null,
    status: "drying",
    floor_plan_id: null,
    assigned_to: null,
    notes: null,
    tech_notes: null,
    latitude: 43.0125,
    longitude: -83.6875,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    room_count: 5,
    photo_count: 18,
    floor_plan_count: 1,
    line_item_count: 12,
  },
  {
    id: "j0000003-0000-0000-0000-000000000003",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260321-003",
    address_line1: "519 Pine Ridge Drive",
    city: "Ann Arbor",
    state: "MI",
    zip: "48104",
    customer_name: "Maria Garcia",
    customer_phone: "(734) 555-0567",
    customer_email: "mgarcia@email.com",
    claim_number: "PROG-2026-7744",
    carrier: "Progressive",
    adjuster_name: "Tom Davis",
    adjuster_phone: "(734) 555-0600",
    adjuster_email: "tdavis@progressive.com",
    loss_type: "water",
    loss_category: "3",
    loss_class: "3",
    loss_cause: "Sewer backup in basement",
    loss_date: dateStr(5),
    home_year_built: null,
    status: "submitted",
    floor_plan_id: null,
    assigned_to: null,
    notes: null,
    tech_notes: "Category 3 — full PPE required. Extracted standing water with truck mount. Removed all affected carpet, pad, and drywall to 4ft. Applied antimicrobial and set containment.",
    latitude: 42.2808,
    longitude: -83.7430,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(0),
    room_count: 2,
    photo_count: 24,
    floor_plan_count: 0,
    line_item_count: 18,
  },
  {
    id: "j0000004-0000-0000-0000-000000000004",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260326-004",
    address_line1: "202 Cedar Way",
    city: "Detroit",
    state: "MI",
    zip: "48226",
    customer_name: "David Kim",
    customer_phone: "(313) 555-0891",
    customer_email: "dkim@email.com",
    claim_number: null,
    carrier: "USAA",
    adjuster_name: null,
    adjuster_phone: null,
    adjuster_email: null,
    loss_type: "water",
    loss_category: "2",
    loss_class: "1",
    loss_cause: "Water heater leak",
    loss_date: dateStr(2),
    home_year_built: null,
    status: "new",
    floor_plan_id: null,
    assigned_to: null,
    notes: null,
    tech_notes: null,
    latitude: 42.3314,
    longitude: -83.0458,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(0),
    room_count: 1,
    photo_count: 12,
    floor_plan_count: 0,
    line_item_count: 0,
  },
  {
    id: "j0000005-0000-0000-0000-000000000005",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260320-005",
    address_line1: "315 Elm Boulevard",
    city: "Lansing",
    state: "MI",
    zip: "48910",
    customer_name: "Lisa Thompson",
    customer_phone: "(517) 555-0345",
    customer_email: "lthompson@email.com",
    claim_number: "SF-2026-3890",
    carrier: "State Farm",
    adjuster_name: "Amy Brown",
    adjuster_phone: "(517) 555-0401",
    adjuster_email: "abrown@statefarm.com",
    loss_type: "water",
    loss_category: "1",
    loss_class: "1",
    loss_cause: "Ice dam roof leak",
    loss_date: dateStr(6),
    home_year_built: null,
    status: "drying",
    floor_plan_id: null,
    assigned_to: null,
    notes: null,
    tech_notes: "Minor attic leak from ice dam. Affected ceiling drywall in master bedroom and hallway. Set 2 air movers and 1 dehu.",
    latitude: 42.7195,
    longitude: -84.5475,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(6),
    updated_at: daysAgo(1),
    room_count: 2,
    photo_count: 8,
    floor_plan_count: 0,
    line_item_count: 6,
  },
  {
    id: "j0000006-0000-0000-0000-000000000006",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260319-006",
    address_line1: "777 Birch Lane",
    city: "East Lansing",
    state: "MI",
    zip: "48823",
    customer_name: "Paul Anderson",
    customer_phone: "(517) 555-0678",
    customer_email: "panderson@email.com",
    claim_number: "ERIE-2026-5521",
    carrier: "Erie Insurance",
    adjuster_name: "Chris Lee",
    adjuster_phone: "(517) 555-0700",
    adjuster_email: "clee@erieinsurance.com",
    loss_type: "water",
    loss_category: "2",
    loss_class: "2",
    loss_cause: "Washing machine overflow",
    loss_date: dateStr(7),
    home_year_built: null,
    status: "drying",
    floor_plan_id: null,
    assigned_to: null,
    notes: null,
    tech_notes: null,
    latitude: 42.7369,
    longitude: -84.4839,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
    room_count: 3,
    photo_count: 15,
    floor_plan_count: 1,
    line_item_count: 9,
  },
  {
    id: "j0000007-0000-0000-0000-000000000007",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "mitigation",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260326-007",
    address_line1: "450 Walnut Court",
    city: "Lansing",
    state: "MI",
    zip: "48911",
    customer_name: "Tom Reynolds",
    customer_phone: "(517) 555-0999",
    customer_email: "treynolds@email.com",
    claim_number: null,
    carrier: "Farmers Insurance",
    adjuster_name: null,
    adjuster_phone: null,
    adjuster_email: null,
    loss_type: "water",
    loss_category: "3",
    loss_class: null,
    loss_cause: "Toilet overflow — commercial property",
    loss_date: dateStr(0),
    home_year_built: null,
    status: "new",
    floor_plan_id: null,
    assigned_to: null,
    notes: "Emergency call — dispatched immediately",
    tech_notes: null,
    latitude: 42.7085,
    longitude: -84.5655,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    room_count: 0,
    photo_count: 0,
    floor_plan_count: 0,
    line_item_count: 0,
  },
  // ── Reconstruction Jobs ──
  {
    id: "j0000008-0000-0000-0000-000000000008",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "reconstruction",
    linked_job_id: "j0000003-0000-0000-0000-000000000003",
    linked_job_summary: {
      id: "j0000003-0000-0000-0000-000000000003",
      job_number: "JOB-20260321-003",
      job_type: "mitigation",
      status: "submitted",
    },
    job_number: "JOB-20260401-008",
    address_line1: "519 Pine Ridge Drive",
    city: "Ann Arbor",
    state: "MI",
    zip: "48104",
    customer_name: "Maria Garcia",
    customer_phone: "(734) 555-0567",
    customer_email: "mgarcia@email.com",
    claim_number: "PROG-2026-7744",
    carrier: "Progressive",
    adjuster_name: "Tom Davis",
    adjuster_phone: "(734) 555-0600",
    adjuster_email: "tdavis@progressive.com",
    loss_type: "water",
    loss_category: null,
    loss_class: null,
    loss_cause: "Sewer backup in basement — reconstruction after mitigation",
    loss_date: dateStr(5),
    home_year_built: null,
    status: "in_progress",
    floor_plan_id: null,
    assigned_to: null,
    notes: "Linked to mitigation JOB-20260321-003. Demo complete, rough-in underway.",
    tech_notes: null,
    latitude: 42.2808,
    longitude: -83.7430,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(0),
    room_count: 2,
    photo_count: 6,
    floor_plan_count: 0,
    line_item_count: 8,
  },
  {
    id: "j0000009-0000-0000-0000-000000000009",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "reconstruction",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260403-009",
    address_line1: "1200 Grand River Ave",
    city: "East Lansing",
    state: "MI",
    zip: "48823",
    customer_name: "Kathy Nguyen",
    customer_phone: "(517) 555-0412",
    customer_email: "knguyen@email.com",
    claim_number: "TRAV-2026-8821",
    carrier: "Travelers",
    adjuster_name: "Derek Hall",
    adjuster_phone: "(517) 555-0455",
    adjuster_email: "dhall@travelers.com",
    loss_type: "fire",
    loss_category: null,
    loss_class: null,
    loss_cause: "Kitchen fire — rebuild required",
    loss_date: dateStr(14),
    home_year_built: null,
    status: "scoping",
    floor_plan_id: null,
    assigned_to: null,
    notes: "Insurance-referred standalone reconstruction. No prior mitigation job in system.",
    tech_notes: null,
    latitude: 42.7369,
    longitude: -84.4839,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(4),
    updated_at: daysAgo(1),
    room_count: 4,
    photo_count: 14,
    floor_plan_count: 1,
    line_item_count: 0,
  },
  {
    id: "j0000010-0000-0000-0000-000000000010",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "reconstruction",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260405-010",
    address_line1: "88 Washtenaw Ave",
    city: "Ypsilanti",
    state: "MI",
    zip: "48197",
    customer_name: "Derek Lawson",
    customer_phone: "(734) 555-0811",
    customer_email: "dlawson@email.com",
    claim_number: "USAA-2026-4410",
    carrier: "USAA",
    adjuster_name: "Robin Patel",
    adjuster_phone: "(734) 555-0822",
    adjuster_email: "rpatel@usaa.com",
    loss_type: "water",
    loss_category: null,
    loss_class: null,
    loss_cause: "Basement flood — full rebuild after mitigation",
    loss_date: dateStr(20),
    home_year_built: null,
    status: "new",
    floor_plan_id: null,
    assigned_to: null,
    notes: "Waiting on insurance approval to begin.",
    tech_notes: null,
    latitude: 42.2411,
    longitude: -83.6130,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
    room_count: 0,
    photo_count: 0,
    floor_plan_count: 0,
    line_item_count: 0,
  },
  {
    id: "j0000011-0000-0000-0000-000000000011",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "reconstruction",
    linked_job_id: "j0000005-0000-0000-0000-000000000005",
    linked_job_summary: {
      id: "j0000005-0000-0000-0000-000000000005",
      job_number: "JOB-20260320-005",
      job_type: "mitigation",
      status: "drying",
    },
    job_number: "JOB-20260406-011",
    address_line1: "315 Elm Boulevard",
    city: "Lansing",
    state: "MI",
    zip: "48910",
    customer_name: "Lisa Thompson",
    customer_phone: "(517) 555-0345",
    customer_email: "lthompson@email.com",
    claim_number: "SF-2026-3890",
    carrier: "State Farm",
    adjuster_name: "Amy Brown",
    adjuster_phone: "(517) 555-0401",
    adjuster_email: "abrown@statefarm.com",
    loss_type: "water",
    loss_category: null,
    loss_class: null,
    loss_cause: "Ice dam roof leak — ceiling and wall rebuild",
    loss_date: dateStr(6),
    home_year_built: null,
    status: "complete",
    floor_plan_id: null,
    assigned_to: null,
    notes: "Reconstruction complete, generating final report.",
    tech_notes: "All drywall, paint, and insulation replaced. Customer signed off.",
    latitude: 42.7195,
    longitude: -84.5475,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(0),
    room_count: 2,
    photo_count: 22,
    floor_plan_count: 0,
    line_item_count: 12,
  },
  {
    id: "j0000012-0000-0000-0000-000000000012",
    company_id: COMPANY_ID,
    property_id: null,
    job_type: "reconstruction",
    linked_job_id: null,
    linked_job_summary: null,
    job_number: "JOB-20260402-012",
    address_line1: "2100 Michigan Ave",
    city: "Dearborn",
    state: "MI",
    zip: "48124",
    customer_name: "Frank Morales",
    customer_phone: "(313) 555-0277",
    customer_email: "fmorales@email.com",
    claim_number: "TRAV-2026-9102",
    carrier: "Travelers",
    adjuster_name: "Linda Chen",
    adjuster_phone: "(313) 555-0290",
    adjuster_email: "lchen@travelers.com",
    loss_type: "fire",
    loss_category: null,
    loss_class: null,
    loss_cause: "Electrical fire in garage — partial rebuild",
    loss_date: dateStr(30),
    home_year_built: null,
    status: "in_progress",
    floor_plan_id: null,
    assigned_to: null,
    notes: "Framing and electrical rough-in complete. Drywall phase starting.",
    tech_notes: null,
    latitude: 42.3223,
    longitude: -83.1763,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
    room_count: 3,
    photo_count: 18,
    floor_plan_count: 1,
    line_item_count: 15,
  },
];

// ─── Reconstruction Phases ───────────────────────────────────────────
export const mockReconPhases: ReconPhase[] = [
  // ── Job 8: 519 Pine Ridge Drive (in_progress — demo done, rough-in active) ──
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Demo", status: "complete", sort_order: 0, started_at: daysAgo(2), completed_at: daysAgo(1), notes: "All affected drywall and flooring removed", created_at: daysAgo(2), updated_at: daysAgo(1) },
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Rough-in", status: "in_progress", sort_order: 1, started_at: daysAgo(1), completed_at: null, notes: "Electrical and plumbing rough-in underway", created_at: daysAgo(1), updated_at: daysAgo(0) },
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Drywall", status: "pending", sort_order: 2, started_at: null, completed_at: null, notes: null, created_at: daysAgo(2), updated_at: daysAgo(2) },
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Paint", status: "pending", sort_order: 3, started_at: null, completed_at: null, notes: null, created_at: daysAgo(2), updated_at: daysAgo(2) },
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Flooring", status: "pending", sort_order: 4, started_at: null, completed_at: null, notes: null, created_at: daysAgo(2), updated_at: daysAgo(2) },
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Trim & Finish", status: "pending", sort_order: 5, started_at: null, completed_at: null, notes: null, created_at: daysAgo(2), updated_at: daysAgo(2) },
  { id: uuid(), job_id: "j0000008-0000-0000-0000-000000000008", company_id: COMPANY_ID, phase_name: "Final Inspection", status: "pending", sort_order: 6, started_at: null, completed_at: null, notes: null, created_at: daysAgo(2), updated_at: daysAgo(2) },
  // ── Job 9: 1200 Grand River Ave (scoping — all phases pending) ──
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Demo", status: "pending", sort_order: 0, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Rough-in", status: "pending", sort_order: 1, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Drywall", status: "pending", sort_order: 2, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Paint", status: "pending", sort_order: 3, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Flooring", status: "pending", sort_order: 4, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Trim & Finish", status: "pending", sort_order: 5, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
  { id: uuid(), job_id: "j0000009-0000-0000-0000-000000000009", company_id: COMPANY_ID, phase_name: "Final Inspection", status: "pending", sort_order: 6, started_at: null, completed_at: null, notes: null, created_at: daysAgo(4), updated_at: daysAgo(4) },
];

// ─── Rooms (all jobs) ────────────────────────────────────────────────
export const mockRooms: Room[] = [
  // ── Job 1: 123 Oak Street (3 rooms) ──
  {
    id: "r0000001-0000-0000-0000-000000000001",
    job_id: mockJobs[0].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Master Bedroom",
    length_ft: 10.5,
    width_ft: 15,
    height_ft: 8,
    square_footage: 157.5,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 3,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Carpet and pad removed. Flood cut 2ft.",
    sort_order: 0,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
  },
  {
    id: "r0000002-0000-0000-0000-000000000002",
    job_id: mockJobs[0].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Kitchen",
    length_ft: 12,
    width_ft: 9,
    height_ft: 8,
    square_footage: 108,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Source room — dishwasher supply line.",
    sort_order: 1,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
  },
  {
    id: "r0000003-0000-0000-0000-000000000003",
    job_id: mockJobs[0].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Hallway",
    length_ft: 3,
    width_ft: 12,
    height_ft: 8,
    square_footage: 36,
    water_category: "2",
    water_class: "1",
    dry_standard: 16,
    equipment_air_movers: 1,
    equipment_dehus: 0,
    room_sketch_data: null,
    notes: null,
    sort_order: 2,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
  },

  // ── Job 2: 842 Maple Avenue (5 rooms) ──
  {
    id: "r0000004-0000-0000-0000-000000000002",
    job_id: mockJobs[1].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Bathroom",
    length_ft: 8,
    width_ft: 6,
    height_ft: 8,
    square_footage: 48,
    water_category: "1",
    water_class: "2",
    dry_standard: 14,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Source room — pipe burst behind vanity wall.",
    sort_order: 0,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000005-0000-0000-0000-000000000002",
    job_id: mockJobs[1].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Hallway",
    length_ft: 4,
    width_ft: 10,
    height_ft: 8,
    square_footage: 40,
    water_category: "1",
    water_class: "1",
    dry_standard: 14,
    equipment_air_movers: 1,
    equipment_dehus: 0,
    room_sketch_data: null,
    notes: null,
    sort_order: 1,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000006-0000-0000-0000-000000000002",
    job_id: mockJobs[1].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Laundry Room",
    length_ft: 6,
    width_ft: 8,
    height_ft: 8,
    square_footage: 48,
    water_category: "1",
    water_class: "2",
    dry_standard: 14,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Water traveled through floor joists from bathroom above.",
    sort_order: 2,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000007-0000-0000-0000-000000000002",
    job_id: mockJobs[1].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Living Room",
    length_ft: 14,
    width_ft: 18,
    height_ft: 9,
    square_footage: 252,
    water_category: "1",
    water_class: "2",
    dry_standard: 14,
    equipment_air_movers: 4,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Ceiling stain from second floor leak. Removed wet insulation.",
    sort_order: 3,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000008-0000-0000-0000-000000000002",
    job_id: mockJobs[1].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Basement",
    length_ft: 20,
    width_ft: 24,
    height_ft: 7,
    square_footage: 480,
    water_category: "1",
    water_class: "3",
    dry_standard: 14,
    equipment_air_movers: 6,
    equipment_dehus: 2,
    room_sketch_data: null,
    notes: "Standing water pooled at drain. Carpet saturated full area.",
    sort_order: 4,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },

  // ── Job 3: 519 Pine Ridge Drive (2 rooms) ──
  {
    id: "r0000009-0000-0000-0000-000000000003",
    job_id: mockJobs[2].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Basement",
    length_ft: 22,
    width_ft: 18,
    height_ft: 7,
    square_footage: 396,
    water_category: "3",
    water_class: "3",
    dry_standard: 12,
    equipment_air_movers: 8,
    equipment_dehus: 2,
    room_sketch_data: null,
    notes: "Full demo — carpet, pad, drywall to 4ft. Antimicrobial applied.",
    sort_order: 0,
    reading_count: 0,
    latest_reading_date: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000010-0000-0000-0000-000000000003",
    job_id: mockJobs[2].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Utility Room",
    length_ft: 8,
    width_ft: 10,
    height_ft: 7,
    square_footage: 80,
    water_category: "3",
    water_class: "3",
    dry_standard: 12,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Sewer backup point of entry. HVAC contamination check required.",
    sort_order: 1,
    reading_count: 0,
    latest_reading_date: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },

  // ── Job 4: 202 Cedar Way (1 room) ──
  {
    id: "r0000011-0000-0000-0000-000000000004",
    job_id: mockJobs[3].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Garage",
    length_ft: 20,
    width_ft: 22,
    height_ft: 9,
    square_footage: 440,
    water_category: "2",
    water_class: "1",
    dry_standard: 16,
    equipment_air_movers: 3,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Water heater in corner. Concrete floor, drywall affected 1ft.",
    sort_order: 0,
    reading_count: 0,
    latest_reading_date: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(0),
  },

  // ── Job 5: 315 Elm Boulevard (2 rooms) ──
  {
    id: "r0000012-0000-0000-0000-000000000005",
    job_id: mockJobs[4].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Master Bedroom",
    length_ft: 14,
    width_ft: 12,
    height_ft: 8,
    square_footage: 168,
    water_category: "1",
    water_class: "1",
    dry_standard: 14,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Ceiling drywall stained from attic leak. No structural damage.",
    sort_order: 0,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(6),
    updated_at: daysAgo(0),
  },
  {
    id: "r0000013-0000-0000-0000-000000000005",
    job_id: mockJobs[4].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Hallway",
    length_ft: 4,
    width_ft: 14,
    height_ft: 8,
    square_footage: 56,
    water_category: "1",
    water_class: "1",
    dry_standard: 14,
    equipment_air_movers: 1,
    equipment_dehus: 0,
    room_sketch_data: null,
    notes: "Minor ceiling drip stain. Monitored only.",
    sort_order: 1,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(6),
    updated_at: daysAgo(0),
  },

  // ── Job 6: 777 Birch Lane (3 rooms) ──
  {
    id: "r0000014-0000-0000-0000-000000000006",
    job_id: mockJobs[5].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Laundry Room",
    length_ft: 7,
    width_ft: 8,
    height_ft: 8,
    square_footage: 56,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Source — washing machine drain hose disconnected. Floor saturated.",
    sort_order: 0,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000015-0000-0000-0000-000000000006",
    job_id: mockJobs[5].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Kitchen",
    length_ft: 10,
    width_ft: 12,
    height_ft: 8,
    square_footage: 120,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 3,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Water migrated under cabinets. Toe kicks removed for drying.",
    sort_order: 1,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
  {
    id: "r0000016-0000-0000-0000-000000000006",
    job_id: mockJobs[5].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Basement",
    length_ft: 16,
    width_ft: 20,
    height_ft: 7,
    square_footage: 320,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 4,
    equipment_dehus: 2,
    room_sketch_data: null,
    notes: "Water seeped through floor to basement ceiling joists.",
    sort_order: 2,
    reading_count: 2,
    latest_reading_date: dateStr(1),
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },

  // Job 7: 450 Walnut Court — 0 rooms (emergency just dispatched)
];


// ─── Photos (picsum.photos with seeded URLs) ─────────────────────────

function generatePhotos(
  jobIndex: number,
  count: number,
  rooms: { id: string; name: string }[],
  daysBack: number,
): Photo[] {
  const jobId = mockJobs[jobIndex].id;
  return Array.from({ length: count }, (_, i) => {
    // Distribute photos across rooms; last few untagged
    let roomId: string | null = null;
    let roomName: string | null = null;
    if (rooms.length > 0 && i < count - Math.max(0, Math.floor(count * 0.15))) {
      const rIdx = i % rooms.length;
      roomId = rooms[rIdx].id;
      roomName = rooms[rIdx].name;
    }
    return {
      id: `p${String(jobIndex + 1).padStart(3, "0")}-${String(i + 1).padStart(4, "0")}-0000-0000-000000000001`,
      job_id: jobId,
      company_id: COMPANY_ID,
      room_id: roomId,
      room_name: roomName,
      storage_url: `https://picsum.photos/seed/crewmatic-${jobIndex + 1}-${i}/400/300`,
      filename: `IMG_${String(3000 + jobIndex * 100 + i)}.jpg`,
      caption: null,
      photo_type: i % 8 === 0 ? "equipment" as const : i % 6 === 0 ? "before" as const : "damage" as const,
      selected_for_ai: i < Math.ceil(count * 0.5),
      uploaded_at: daysAgo(daysBack - Math.floor(i / Math.max(1, Math.ceil(count / 3)))),
    };
  });
}

export const mockPhotos: Photo[] = [
  // Job 1: 42 photos
  ...generatePhotos(0, 42, [
    { id: mockRooms[0].id, name: "Master Bedroom" },
    { id: mockRooms[1].id, name: "Kitchen" },
    { id: mockRooms[2].id, name: "Hallway" },
  ], 3),
  // Job 2: 18 photos
  ...generatePhotos(1, 18, [
    { id: "r0000004-0000-0000-0000-000000000002", name: "Bathroom" },
    { id: "r0000005-0000-0000-0000-000000000002", name: "Hallway" },
    { id: "r0000006-0000-0000-0000-000000000002", name: "Laundry Room" },
    { id: "r0000007-0000-0000-0000-000000000002", name: "Living Room" },
    { id: "r0000008-0000-0000-0000-000000000002", name: "Basement" },
  ], 5),
  // Job 3: 24 photos
  ...generatePhotos(2, 24, [
    { id: "r0000009-0000-0000-0000-000000000003", name: "Basement" },
    { id: "r0000010-0000-0000-0000-000000000003", name: "Utility Room" },
  ], 5),
  // Job 4: 12 photos
  ...generatePhotos(3, 12, [
    { id: "r0000011-0000-0000-0000-000000000004", name: "Garage" },
  ], 2),
  // Job 5: 8 photos
  ...generatePhotos(4, 8, [
    { id: "r0000012-0000-0000-0000-000000000005", name: "Master Bedroom" },
    { id: "r0000013-0000-0000-0000-000000000005", name: "Hallway" },
  ], 6),
  // Job 6: 15 photos
  ...generatePhotos(5, 15, [
    { id: "r0000014-0000-0000-0000-000000000006", name: "Laundry Room" },
    { id: "r0000015-0000-0000-0000-000000000006", name: "Kitchen" },
    { id: "r0000016-0000-0000-0000-000000000006", name: "Basement" },
  ], 7),
  // Job 7: 0 photos (emergency just dispatched)
];

// ─── Events (activity feed for all jobs) ─────────────────────────────
export const mockEvents: Event[] = [
  // Job 1 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "photo_uploaded", user_id: "user1", is_ai: false, event_data: { count: 5, room_name: "Master Bedroom" }, created_at: hoursAgo(2) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "moisture_reading_added", user_id: "user1", is_ai: false, event_data: { room_name: "Master Bedroom", day_number: 3 }, created_at: hoursAgo(3) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "ai_sketch_cleanup", user_id: null, is_ai: true, event_data: { rooms_created: 3 }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "room_added", user_id: "user1", is_ai: false, event_data: { room_name: "Hallway" }, created_at: daysAgo(2) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "room_added", user_id: "user1", is_ai: false, event_data: { room_name: "Kitchen" }, created_at: daysAgo(2) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "photo_uploaded", user_id: "user1", is_ai: false, event_data: { count: 18, room_name: "Kitchen" }, created_at: daysAgo(2) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(3) },

  // Job 2 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "moisture_reading_added", user_id: "user2", is_ai: false, event_data: { room_name: "Bathroom", day_number: 2 }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "ai_photo_analysis", user_id: null, is_ai: true, event_data: { line_items_generated: 12, duration_ms: 4200 }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "photo_uploaded", user_id: "user2", is_ai: false, event_data: { count: 10, room_name: "Basement" }, created_at: daysAgo(2) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "job_status_changed", user_id: "user1", is_ai: false, event_data: { from: "new", to: "drying" }, created_at: daysAgo(2) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "room_added", user_id: "user2", is_ai: false, event_data: { room_name: "Basement" }, created_at: daysAgo(3) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(5) },

  // Job 3 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[2].id, event_type: "report_generated", user_id: "user1", is_ai: false, event_data: { report_type: "mitigation_invoice" }, created_at: hoursAgo(6) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[2].id, event_type: "job_status_changed", user_id: "user1", is_ai: false, event_data: { from: "complete", to: "submitted" }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[2].id, event_type: "photo_uploaded", user_id: "user1", is_ai: false, event_data: { count: 14, room_name: "Basement" }, created_at: daysAgo(3) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[2].id, event_type: "room_added", user_id: "user1", is_ai: false, event_data: { room_name: "Utility Room" }, created_at: daysAgo(4) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[2].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(5) },

  // Job 4 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[3].id, event_type: "photo_uploaded", user_id: "user1", is_ai: false, event_data: { count: 12, room_name: "Garage" }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[3].id, event_type: "room_added", user_id: "user1", is_ai: false, event_data: { room_name: "Garage" }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[3].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(2) },

  // Job 5 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[4].id, event_type: "moisture_reading_added", user_id: "user1", is_ai: false, event_data: { room_name: "Master Bedroom", day_number: 3 }, created_at: hoursAgo(5) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[4].id, event_type: "job_status_changed", user_id: "user1", is_ai: false, event_data: { from: "new", to: "drying" }, created_at: daysAgo(3) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[4].id, event_type: "photo_uploaded", user_id: "user1", is_ai: false, event_data: { count: 8, room_name: "Master Bedroom" }, created_at: daysAgo(5) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[4].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(6) },

  // Job 6 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[5].id, event_type: "moisture_reading_added", user_id: "user2", is_ai: false, event_data: { room_name: "Laundry Room", day_number: 2 }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[5].id, event_type: "photo_uploaded", user_id: "user2", is_ai: false, event_data: { count: 15, room_name: "Kitchen" }, created_at: daysAgo(3) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[5].id, event_type: "room_added", user_id: "user2", is_ai: false, event_data: { room_name: "Basement" }, created_at: daysAgo(5) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[5].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(7) },

  // Job 7 events
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[6].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: hoursAgo(1) },
];

// ─── Dashboard Data ──────────────────────────────────────────────────
export const mockDashboardKPIs: DashboardKPIs = {
  active_jobs: 7,
  active_jobs_change: 2,
  revenue_mtd: 24850,
  revenue_change_pct: 12,
  outstanding_ar: 41200,
  avg_days_to_pay: 34,
  avg_cycle_days: 6.2,
  cycle_change_days: -0.8,
};

export const mockPipeline: PipelineStageData[] = [
  { stage: "new", label: "New", count: 2, amount: 0, color: "#dc2626" },
  { stage: "contracted", label: "Contracted", count: 0, amount: 0, color: "#f59e0b" },
  { stage: "mitigation", label: "Mitigation", count: 1, amount: 4200, color: "#e85d26" },
  { stage: "drying", label: "Drying", count: 3, amount: 28500, color: "#2563eb" },
  { stage: "complete", label: "Job Complete", count: 0, amount: 0, color: "#6b7280" },
  { stage: "submitted", label: "Submitted", count: 1, amount: 12600, color: "#0891b2" },
  { stage: "collected", label: "Collected", count: 4, amount: 41200, color: "#16a34a" },
];

export const mockPriorityTasks: PriorityTask[] = [
  // New
  { id: "t1", job_id: mockJobs[6].id, address: "450 Walnut Court", description: "Emergency dispatch, toilet overflow — ETA 2:30 PM", priority: "critical" },
  { id: "t3", job_id: mockJobs[3].id, address: "202 Cedar Way", description: "Day 2, just got the call — heading to site", priority: "warning" },
  // Mitigation
  { id: "t2", job_id: mockJobs[0].id, address: "123 Oak Street", description: "Day 3, on site — equipment set, taking photos", priority: "warning" },
  // Drying
  { id: "t4", job_id: mockJobs[1].id, address: "842 Maple Avenue", description: "Day 5, drying in progress — readings overdue 24h", priority: "normal" },
  { id: "t5", job_id: mockJobs[4].id, address: "315 Elm Boulevard", description: "Day 6, drying — equipment pickup scheduled tomorrow", priority: "normal" },
  { id: "t6", job_id: mockJobs[5].id, address: "777 Birch Lane", description: "Day 7, drying — 3 rooms monitored", priority: "normal" },
  // Submitted
  { id: "t7", job_id: mockJobs[2].id, address: "519 Pine Ridge Drive", description: "Submitted to adjuster — awaiting payment", priority: "low" },
];

export const mockTeamMembers: TeamMember[] = [
  { id: "u1", name: "Brett S.", avatar_url: null, current_job_address: "123 Oak Street", status: "on_site" },
  { id: "u2", name: "Mike T.", avatar_url: null, current_job_address: "842 Maple Avenue", status: "on_site" },
  { id: "u3", name: "Jake R.", avatar_url: null, status: "available", current_job_address: null },
];
