// Realistic mock data for Crewmatic — Lansing, MI restoration contractor
// This file is the single source of mock data. Swap to real API calls in hooks.

import type {
  Job, JobDetail, Room, Photo, MoistureReading, MoisturePoint, DehuOutput,
  Event, DashboardKPIs, PipelineStageData, PriorityTask, TeamMember, FloorPlan,
} from "./types";

// ─── Helpers ──────────────────────────────────────────────────────────
const uuid = () => crypto.randomUUID();
const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const dateStr = (n: number) => new Date(Date.now() - n * 86400000).toISOString().split("T")[0];

const COMPANY_ID = "c0000000-0000-0000-0000-000000000001";

// ─── Jobs ─────────────────────────────────────────────────────────────
export const mockJobs: JobDetail[] = [
  {
    id: "j0000001-0000-0000-0000-000000000001",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260324-001",
    address_line1: "123 Oak Street",
    city: "Lansing",
    state: "MI",
    zip: "48912",
    customer_name: "Jane Smith",
    customer_phone: "(517) 555-0142",
    customer_email: "jane.smith@email.com",
    claim_number: "SF-2026-4521",
    carrier: "State Farm",
    adjuster_name: "Mike Johnson",
    adjuster_phone: "(517) 555-0199",
    adjuster_email: "mjohnson@statefarm.com",
    loss_type: "water",
    loss_category: "2",
    loss_class: "2",
    loss_cause: "Dishwasher supply line failure",
    loss_date: dateStr(3),
    status: "needs_scope",
    assigned_to: null,
    notes: null,
    tech_notes: "Lifted carpet and pad in master bedroom. Flood cut drywall 2ft from floor. Applied antimicrobial treatment to all exposed surfaces. Wore N95 respirator and Tyvek suit.",
    latitude: 42.7325,
    longitude: -84.5555,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
    room_count: 3,
    photo_count: 42,
    floor_plan_count: 1,
    line_item_count: 0,
  },
  {
    id: "j0000002-0000-0000-0000-000000000002",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260323-002",
    address_line1: "842 Maple Avenue",
    city: "Flint",
    state: "MI",
    zip: "48503",
    customer_name: "Robert Chen",
    customer_phone: "(810) 555-0234",
    customer_email: "rchen@email.com",
    claim_number: "ALT-2026-1198",
    carrier: "Allstate",
    adjuster_name: "Sarah Williams",
    adjuster_phone: "(810) 555-0288",
    adjuster_email: "swilliams@allstate.com",
    loss_type: "water",
    loss_category: "1",
    loss_class: "2",
    loss_cause: "Frozen pipe burst — second floor bathroom",
    loss_date: dateStr(5),
    status: "scoped",
    assigned_to: null,
    notes: null,
    tech_notes: null,
    latitude: 43.0125,
    longitude: -83.6875,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    room_count: 5,
    photo_count: 18,
    floor_plan_count: 1,
    line_item_count: 12,
  },
  {
    id: "j0000003-0000-0000-0000-000000000003",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260321-003",
    address_line1: "519 Pine Ridge Drive",
    city: "Ann Arbor",
    state: "MI",
    zip: "48104",
    customer_name: "Maria Garcia",
    customer_phone: "(734) 555-0567",
    customer_email: "mgarcia@email.com",
    claim_number: "PROG-2026-7744",
    carrier: "Progressive",
    adjuster_name: "Tom Davis",
    adjuster_phone: "(734) 555-0600",
    adjuster_email: "tdavis@progressive.com",
    loss_type: "water",
    loss_category: "3",
    loss_class: "3",
    loss_cause: "Sewer backup in basement",
    loss_date: dateStr(5),
    status: "submitted",
    assigned_to: null,
    notes: null,
    tech_notes: "Category 3 — full PPE required. Extracted standing water with truck mount. Removed all affected carpet, pad, and drywall to 4ft. Applied antimicrobial and set containment.",
    latitude: 42.2808,
    longitude: -83.7430,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(0),
    room_count: 2,
    photo_count: 24,
    floor_plan_count: 0,
    line_item_count: 18,
  },
  {
    id: "j0000004-0000-0000-0000-000000000004",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260326-004",
    address_line1: "202 Cedar Way",
    city: "Detroit",
    state: "MI",
    zip: "48226",
    customer_name: "David Kim",
    customer_phone: "(313) 555-0891",
    customer_email: "dkim@email.com",
    claim_number: null,
    carrier: "USAA",
    adjuster_name: null,
    adjuster_phone: null,
    adjuster_email: null,
    loss_type: "water",
    loss_category: "2",
    loss_class: "1",
    loss_cause: "Water heater leak",
    loss_date: dateStr(2),
    status: "needs_scope",
    assigned_to: null,
    notes: null,
    tech_notes: null,
    latitude: 42.3314,
    longitude: -83.0458,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(0),
    room_count: 1,
    photo_count: 12,
    floor_plan_count: 0,
    line_item_count: 0,
  },
  {
    id: "j0000005-0000-0000-0000-000000000005",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260320-005",
    address_line1: "315 Elm Boulevard",
    city: "Lansing",
    state: "MI",
    zip: "48910",
    customer_name: "Lisa Thompson",
    customer_phone: "(517) 555-0345",
    customer_email: "lthompson@email.com",
    claim_number: "SF-2026-3890",
    carrier: "State Farm",
    adjuster_name: "Amy Brown",
    adjuster_phone: "(517) 555-0401",
    adjuster_email: "abrown@statefarm.com",
    loss_type: "water",
    loss_category: "1",
    loss_class: "1",
    loss_cause: "Ice dam roof leak",
    loss_date: dateStr(6),
    status: "scoped",
    assigned_to: null,
    notes: null,
    tech_notes: "Minor attic leak from ice dam. Affected ceiling drywall in master bedroom and hallway. Set 2 air movers and 1 dehu.",
    latitude: 42.7195,
    longitude: -84.5475,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(6),
    updated_at: daysAgo(1),
    room_count: 2,
    photo_count: 8,
    floor_plan_count: 0,
    line_item_count: 6,
  },
  {
    id: "j0000006-0000-0000-0000-000000000006",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260319-006",
    address_line1: "777 Birch Lane",
    city: "East Lansing",
    state: "MI",
    zip: "48823",
    customer_name: "Paul Anderson",
    customer_phone: "(517) 555-0678",
    customer_email: "panderson@email.com",
    claim_number: "ERIE-2026-5521",
    carrier: "Erie Insurance",
    adjuster_name: "Chris Lee",
    adjuster_phone: "(517) 555-0700",
    adjuster_email: "clee@erieinsurance.com",
    loss_type: "water",
    loss_category: "2",
    loss_class: "2",
    loss_cause: "Washing machine overflow",
    loss_date: dateStr(7),
    status: "scoped",
    assigned_to: null,
    notes: null,
    tech_notes: null,
    latitude: 42.7369,
    longitude: -84.4839,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
    room_count: 3,
    photo_count: 15,
    floor_plan_count: 1,
    line_item_count: 9,
  },
  {
    id: "j0000007-0000-0000-0000-000000000007",
    company_id: COMPANY_ID,
    property_id: null,
    job_number: "JOB-20260326-007",
    address_line1: "450 Walnut Court",
    city: "Lansing",
    state: "MI",
    zip: "48911",
    customer_name: "Emergency — no name yet",
    customer_phone: "(517) 555-0999",
    customer_email: null,
    claim_number: null,
    carrier: null,
    adjuster_name: null,
    adjuster_phone: null,
    adjuster_email: null,
    loss_type: "water",
    loss_category: "3",
    loss_class: null,
    loss_cause: "Toilet overflow — commercial property",
    loss_date: dateStr(0),
    status: "needs_scope",
    assigned_to: null,
    notes: "Emergency call — dispatched immediately",
    tech_notes: null,
    latitude: 42.7085,
    longitude: -84.5655,
    created_by: null,
    updated_by: null,
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
    room_count: 0,
    photo_count: 0,
    floor_plan_count: 0,
    line_item_count: 0,
  },
];

// ─── Rooms (for job 1 — 123 Oak Street) ──────────────────────────────
export const mockRooms: Room[] = [
  {
    id: "r0000001-0000-0000-0000-000000000001",
    job_id: mockJobs[0].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Master Bedroom",
    length_ft: 10.5,
    width_ft: 15,
    height_ft: 8,
    square_footage: 157.5,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 3,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Carpet and pad removed. Flood cut 2ft.",
    sort_order: 0,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
  },
  {
    id: "r0000002-0000-0000-0000-000000000002",
    job_id: mockJobs[0].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Kitchen",
    length_ft: 12,
    width_ft: 9,
    height_ft: 8,
    square_footage: 108,
    water_category: "2",
    water_class: "2",
    dry_standard: 16,
    equipment_air_movers: 2,
    equipment_dehus: 1,
    room_sketch_data: null,
    notes: "Source room — dishwasher supply line.",
    sort_order: 1,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
  },
  {
    id: "r0000003-0000-0000-0000-000000000003",
    job_id: mockJobs[0].id,
    company_id: COMPANY_ID,
    floor_plan_id: null,
    room_name: "Hallway",
    length_ft: 3,
    width_ft: 12,
    height_ft: 8,
    square_footage: 36,
    water_category: "2",
    water_class: "1",
    dry_standard: 16,
    equipment_air_movers: 1,
    equipment_dehus: 0,
    room_sketch_data: null,
    notes: null,
    sort_order: 2,
    reading_count: 3,
    latest_reading_date: dateStr(0),
    created_at: daysAgo(3),
    updated_at: daysAgo(0),
  },
];

// ─── Moisture Readings (for Master Bedroom, 3 days) ──────────────────
export const mockReadings: MoistureReading[] = [
  {
    id: uuid(),
    job_id: mockJobs[0].id,
    room_id: mockRooms[0].id,
    company_id: COMPANY_ID,
    reading_date: dateStr(2),
    day_number: 1,
    atmospheric_temp_f: 72,
    atmospheric_rh_pct: 55,
    atmospheric_gpp: 78.2,
    points: [
      { id: uuid(), reading_id: "", location_name: "South wall base", reading_value: 68, meter_photo_url: null, sort_order: 0, created_at: daysAgo(2) },
      { id: uuid(), reading_id: "", location_name: "North wall base", reading_value: 62, meter_photo_url: null, sort_order: 1, created_at: daysAgo(2) },
      { id: uuid(), reading_id: "", location_name: "Subfloor center", reading_value: 74, meter_photo_url: null, sort_order: 2, created_at: daysAgo(2) },
    ],
    dehus: [
      { id: uuid(), reading_id: "", dehu_model: "Dri-Eaz LGR 3500i", rh_out_pct: 48, temp_out_f: 92, sort_order: 0, created_at: daysAgo(2) },
    ],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: uuid(),
    job_id: mockJobs[0].id,
    room_id: mockRooms[0].id,
    company_id: COMPANY_ID,
    reading_date: dateStr(1),
    day_number: 2,
    atmospheric_temp_f: 71,
    atmospheric_rh_pct: 48,
    atmospheric_gpp: 62.4,
    points: [
      { id: uuid(), reading_id: "", location_name: "South wall base", reading_value: 52, meter_photo_url: null, sort_order: 0, created_at: daysAgo(1) },
      { id: uuid(), reading_id: "", location_name: "North wall base", reading_value: 46, meter_photo_url: null, sort_order: 1, created_at: daysAgo(1) },
      { id: uuid(), reading_id: "", location_name: "Subfloor center", reading_value: 64, meter_photo_url: null, sort_order: 2, created_at: daysAgo(1) },
    ],
    dehus: [
      { id: uuid(), reading_id: "", dehu_model: "Dri-Eaz LGR 3500i", rh_out_pct: 42, temp_out_f: 89, sort_order: 0, created_at: daysAgo(1) },
    ],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: uuid(),
    job_id: mockJobs[0].id,
    room_id: mockRooms[0].id,
    company_id: COMPANY_ID,
    reading_date: dateStr(0),
    day_number: 3,
    atmospheric_temp_f: 72,
    atmospheric_rh_pct: 45,
    atmospheric_gpp: 55.1,
    points: [
      { id: uuid(), reading_id: "", location_name: "South wall base", reading_value: 42, meter_photo_url: null, sort_order: 0, created_at: now },
      { id: uuid(), reading_id: "", location_name: "North wall base", reading_value: 38, meter_photo_url: null, sort_order: 1, created_at: now },
      { id: uuid(), reading_id: "", location_name: "Subfloor center", reading_value: 55, meter_photo_url: null, sort_order: 2, created_at: now },
    ],
    dehus: [
      { id: uuid(), reading_id: "", dehu_model: "Dri-Eaz LGR 3500i", rh_out_pct: 38, temp_out_f: 85, sort_order: 0, created_at: now },
    ],
    created_at: now,
    updated_at: now,
  },
];

// ─── Photos (mock URLs — use placeholder images) ─────────────────────
export const mockPhotos: Photo[] = Array.from({ length: 42 }, (_, i) => ({
  id: `p${String(i + 1).padStart(7, "0")}-0000-0000-0000-000000000001`,
  job_id: mockJobs[0].id,
  company_id: COMPANY_ID,
  room_id: i < 12 ? mockRooms[0].id : i < 27 ? mockRooms[1].id : i < 35 ? mockRooms[2].id : null,
  room_name: i < 12 ? "Master Bedroom" : i < 27 ? "Kitchen" : i < 35 ? "Hallway" : null,
  storage_url: `/api/placeholder/${300 + (i % 5) * 20}/${200 + (i % 3) * 20}`,
  filename: `IMG_${String(4200 + i)}.jpg`,
  caption: null,
  photo_type: i % 8 === 0 ? "equipment" : i % 6 === 0 ? "before" : "damage",
  selected_for_ai: i < 20,
  uploaded_at: daysAgo(3 - Math.floor(i / 15)),
}));

// ─── Events (activity feed) ──────────────────────────────────────────
export const mockEvents: Event[] = [
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "photo_uploaded", user_id: "user1", is_ai: false, event_data: { count: 5, room_name: "Master Bedroom" }, created_at: daysAgo(0) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "moisture_reading_added", user_id: "user1", is_ai: false, event_data: { room_name: "Master Bedroom", day_number: 3 }, created_at: daysAgo(0) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "ai_sketch_cleanup", user_id: null, is_ai: true, event_data: { rooms_created: 3 }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[0].id, event_type: "job_created", user_id: "user1", is_ai: false, event_data: {}, created_at: daysAgo(3) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[1].id, event_type: "ai_photo_analysis", user_id: null, is_ai: true, event_data: { line_items_generated: 12, duration_ms: 4200 }, created_at: daysAgo(1) },
  { id: uuid(), company_id: COMPANY_ID, job_id: mockJobs[2].id, event_type: "report_generated", user_id: "user1", is_ai: false, event_data: { report_type: "mitigation_invoice" }, created_at: daysAgo(0) },
];

// ─── Dashboard Data ──────────────────────────────────────────────────
export const mockDashboardKPIs: DashboardKPIs = {
  active_jobs: 7,
  active_jobs_change: 2,
  revenue_mtd: 24850,
  revenue_change_pct: 12,
  outstanding_ar: 41200,
  avg_days_to_pay: 34,
  avg_cycle_days: 6.2,
  cycle_change_days: -0.8,
};

export const mockPipeline: PipelineStageData[] = [
  { stage: "emergency", label: "Emergency", count: 1, amount: 0, color: "#dc2626" },
  { stage: "scoping", label: "Scoping", count: 2, amount: 0, color: "#e85d26" },
  { stage: "drying", label: "Drying", count: 3, amount: 8400, color: "#2563eb" },
  { stage: "documentation", label: "Docs", count: 0, amount: 0, color: "#7c3aed" },
  { stage: "invoiced", label: "Invoiced", count: 1, amount: 12600, color: "#0891b2" },
  { stage: "paid", label: "Paid", count: 4, amount: 18900, color: "#16a34a" },
];

export const mockPriorityTasks: PriorityTask[] = [
  // Emergency
  { id: "t1", job_id: mockJobs[6].id, address: "450 Walnut Court", description: "Emergency dispatch, toilet overflow — ETA 2:30 PM", priority: "critical" },
  // Scoping
  { id: "t2", job_id: mockJobs[0].id, address: "123 Oak Street", description: "Day 3, needs scope — 42 photos ready for AI", priority: "warning" },
  { id: "t3", job_id: mockJobs[3].id, address: "202 Cedar Way", description: "Day 2, needs scope — 12 photos, 1 room", priority: "warning" },
  // Active Drying
  { id: "t4", job_id: mockJobs[1].id, address: "842 Maple Avenue", description: "Day 5, drying in progress — readings overdue 24h", priority: "normal" },
  { id: "t5", job_id: mockJobs[4].id, address: "315 Elm Boulevard", description: "Day 6, drying — equipment pickup scheduled tomorrow", priority: "normal" },
  { id: "t6", job_id: mockJobs[5].id, address: "777 Birch Lane", description: "Day 7, drying — 3 rooms monitored", priority: "normal" },
  // Invoiced
  { id: "t7", job_id: mockJobs[2].id, address: "519 Pine Ridge Drive", description: "Submitted to adjuster — awaiting payment", priority: "low" },
];

export const mockTeamMembers: TeamMember[] = [
  { id: "u1", name: "Brett S.", avatar_url: null, current_job_address: "123 Oak Street", status: "on_site" },
  { id: "u2", name: "Mike T.", avatar_url: null, current_job_address: "842 Maple Avenue", status: "on_site" },
  { id: "u3", name: "Jake R.", avatar_url: null, status: "available", current_job_address: null },
];
